# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Disable git config core.quotepath
        run: git config core.quotepath off
      - name: Install deb packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y nkf shellcheck uchardet
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Check file permissions
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            if [ -x "$f" ]; then
              echo "$f has unnecessary executable permission."
              exit 1
            fi
          done
      - name: Check file name character encoding
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            encoding=$(echo "$f" | uchardet)
            if [ "$encoding" != "ASCII" ]; then
              echo "$f is not ascii file name but $encoding."
              exit 1
            fi
          done
      - name: Check file content character encoding
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            encoding=$(file --brief --mime-encoding "$f")
            case "$encoding" in
              binary | us-ascii)
                file "$f"
                ;;
              *)
                echo "$f is not ascii but $encoding."
                exit 1
                ;;
            esac
          done
          git diff --exit-code
      - name: Run a one-line script
        run: |
          shellcheck -s sh "$0"
          for sh in bash dash ksh zsh sh; do
            shellcheck -s $sh .shrc
          done
