# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Disable git config core.quotepath
        run: git config core.quotepath off
      - name: apt-get
        run: sudo apt-get update && sudo apt-get install shellcheck
      - name: Check file permissions
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            if [ -x "$f" ]; then
              echo "$f has unnecessary executable permission."
              exit 1
            fi
          done
      - name: Check file name character encoding
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            if [ "$(echo "$f" | nkf --guess)" != "ASCII (LF)" ]; then
              echo "$f is non ascii file name."
              exit 1
            fi
          done
      - name: Check file content character encoding
        run: |
          shellcheck -s sh "$0"
          git ls-files | while read -r f; do
            if [ "$(nkf --guess "$f")" != "BINARY" ]; then
              nkf -w -Lu -Z1 --in-place "$f"
            fi
          done
          git diff --exit-code
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          shellcheck -s sh "$0"
          for sh in bash dash ksh sh; do
            shellcheck -s $sh .shrc
          done
